# Wrangler config for Genspark hosted deployment
name = "iqstudio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist-cf/_worker.js"

[assets]
directory = "./dist-cf"
binding = "ASSETS"
